# Generated by Django 2.1.1 on 2018-08-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.jpg', upload_to='avatars/'),
        ),
    ]
