# Generated by Django 2.0.7 on 2018-07-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='image',
            field=models.ImageField(upload_to='blog/images/'),
        ),
    ]
