# Generated by Django 2.0.7 on 2018-07-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180723_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
