# Generated by Django 2.1.1 on 2018-09-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180809_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watch',
            field=models.IntegerField(default=1),
        ),
    ]
