# Generated by Django 2.1.1 on 2018-09-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_watch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='watch',
            new_name='watch_total',
        ),
    ]
