# Generated by Django 2.0.7 on 2018-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180712_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title_pro',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
