# Generated by Django 2.0.7 on 2018-07-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180712_1126'),
        ('portfolio', '0002_auto_20180712_0729'),
    ]

    operations = [
    ]
