# Generated by Django 2.0.7 on 2018-07-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_merge_20180720_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title_pro',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
