# Generated by Django 2.0.7 on 2018-07-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolio_title_pro'),
        ('portfolio', '0003_portfolio_title_pro'),
    ]

    operations = [
    ]
